seismology/web/main/routes/main.py
from flask import Blueprint, redirect, url_for, current_app, make_response, flash
from flask_breadcrumbs import register_breadcrumb
from ..forms.frmLogin import LoginForm
from flask_login import logout_user, login_user
import requests, json
from .auth import User
from . import verifseism


main = Blueprint("main", __name__, url_prefix="/")

@main.route("/")
@register_breadcrumb(main, "breadcrumbs.", "Home")
def index():
    return redirect(url_for("verifseism.index"))

@main.route("/login", methods=["POST"])
def login():
    loginForm = LoginForm()
    if loginForm.validate_on_submit():

        # Enviamos la peticion de logueo con los datos cargados en la variable "data", a la API.
        data = '{"email":"' + loginForm.email.data + '", "password":"' + loginForm.password.data + '"}'
        r = requests.post(current_app.config["API_URL"]+"/auth/login", headers={"content-type":"application/json"}, data = data)

        # Si la peticion se realiza con exito, cargamos los valores devueltos por la API en la variable "user"
        if r.status_code == 200:
            user_data = json.loads(r.text)
            user = User(id = user_data.get("id"), email = user_data.get("email"), admin = user_data.get("admin"))

            # Logueamos al usuario
            login_user(user)

            # Creamos la redireccion y Seteamos la coockie con el TOKEN
            req = make_response(redirect(url_for("main.index")))
            req.set_cookie("access_token", user_data.get("access_token"), httponly=True)
            return req
        else:
            # Si no, mostramos...
            flash("User or password incorrect", "danger")
    return redirect(url_for("main.index"))

@main.route("/logout")
def logout():
    # Creamos la requests, vaciamos la cockie y deslogueamos al usuario.
    req = make_response(redirect(url_for("main.index")))
    req.set_cookie("access_token", "", httponly=True)
    logout_user()
    return req

seismology/web/main/routes/sensor.py
from flask import Blueprint, render_template, current_app, redirect, url_for, request
from flask_breadcrumbs import register_breadcrumb
import requests, json
from flask import jsonify
from flask_login import login_required, LoginManager
from ..utilities.Functions import sendRequest
#from .auth import admin_required
from ..forms.frmSensor import SensorCreateForm, SensorEditForm, SensorFilterForm
from flask import flash

sensor = Blueprint("sensor", __name__, url_prefix="/sensor")

@sensor.route("/")
@login_required
#@admin_required
@register_breadcrumb(sensor,".","Sensors")
def index():

    fact = {}
    fact['perpage'] = 100

    r = sendRequest(method="get",url="/users",auth=True,data=json.dumps(fact))

    filter = SensorFilterForm(request.args, meta={'crsf': False})

    filter.userId.choices = [(item['id'], item['email']) for item in json.loads(r.text)["Users"]]
    filter.userId.choices.insert(0, [0, 'All'])
    fact = {}

    if filter.validate():
        if filter.name.data != None:
            fact['name'] = filter.name.data
        if filter.status.data != None:
            fact['status'] = filter.status.data
        if filter.active.data != None:
            fact['active'] = filter.active.data
        if filter.userId.data != None and filter.userId.data != 0:
            fact['userId'] = filter.userId.data

    if "page" in request.args:
        fact["page"] = request.args.get("page", "")
    else:
        if "page" in fact:
            del fact["page"]

    if 'sort_by' in request.args:
        fact['sort_by'] = request.args.get('sort_by', '')

    r = sendRequest(method="get", url="/sensors", data=json.dumps(fact), auth=True)

    if r.status_code == 200:
        sensors = json.loads(r.text)["Sensors"]
        paginate = {}
        paginate['total'] = json.loads(r.text)['total']
        paginate['pages'] = json.loads(r.text)['pages']
        paginate['current_page'] = json.loads(r.text)['page']
        title = "Sensors"

        return render_template("Sensors.html", title=title, sensors=sensors, filter=filter, pagination=paginate)
    else:
        flash("filtering error", "danger")
        redirect(url_for('main.logout'))


@sensor.route("/view/<int:id>")
@login_required
#@admin_required
@register_breadcrumb(sensor, ".view", "Sensor")
def view(id):

    r = sendRequest(method="get", url="/sensor/" + str(id), auth=True)

    if (r.status_code == 404):
        flash("Sensor not found", "danger")

        return redirect(url_for("sensor.index"))

    sensor = json.loads(r.text)
    title = "Sensor View"

    return render_template("sensor.html", title=title, sensor=sensor)


@sensor.route("/create", methods=["GET", "POST"])
@login_required
#@admin_required
@register_breadcrumb(sensor, ".create", "Create Sensor")
def create():

    form = SensorCreateForm()
    if form.validate_on_submit():
        sensor = {"name": form.name.data, "ip": form.ip.data, "port": form.port.data, "status": form.status.data, "active": form.active.data, "userId": form.userId.data}
        fact = json.dumps(sensor)
        r = sendRequest(method="post", url="/sensors", data=fact, auth=True)

        return redirect(url_for("sensor.index"))
    return render_template("sensorEdit_form.html", form=form)


@sensor.route("/edit/<int:id>", methods=["GET", "POST"])
@login_required
#@admin_required
@register_breadcrumb(sensor, ".edit", "Edit Sensor")
def edit(id):

    form = SensorEditForm()
    req = sendRequest(method="get", url="/users", auth=True)
    users = [(item['id'], item['email']) for item in json.loads(req.text)["Users"]]
    form.userId.choices = users
    form.userId.choices.insert(0, [0, 'Select one user'])

    if not form.is_submitted():
        r = sendRequest(method="get", url="/sensor/"+str(id), auth=True)

        if r.status_code == 404:
            flash("Sensor not found", "danger")
            return redirect(url_for("sensor.index"))

        sensor = json.loads(r.text)

        form.name.data = sensor["name"]
        form.ip.data = sensor["ip"]
        form.port.data = sensor["port"]
        form.status.data = sensor["status"]
        form.active.data = sensor["active"]

        for user_id, user_email in users:
            if sensor["user"]["id"] == user_id:
                form.userId.data = int(user_id)

    if form.validate_on_submit():
        sensor = {"name": form.name.data, "ip": form.ip.data, "port": form.port.data, "status": form.status.data, "active": form.active.data, "userId": form.userId.data}
        fact = json.dumps(sensor)
        r = sendRequest(method="put", url="/sensor/" + str(id), data=fact, auth=True)
        flash("Sensor edited", "success")

        return redirect(url_for("sensor.index"))
    return render_template("sensorEdit_form.html", id=id, form=form)


@sensor.route("/delete/<int:id>")
@login_required
#@admin_required
def delete(id):

    r = sendRequest(method="delete", url="/sensor/"+str(id), auth=True)
    flash("Sensor deleted", "danger")

    return redirect(url_for("sensor.index"))

seismology/web/main/routes/user.py
from flask import Blueprint, render_template, current_app, redirect, url_for, flash, request
from flask_breadcrumbs import register_breadcrumb
from ..forms.frmUser import UserEditForm, UserCreateForm
import json
from flask_login import login_required, LoginManager
from ..utilities.Functions import sendRequest
#from .auth import admin_required


user = Blueprint("user", __name__, url_prefix="/user")

@user.route("/")
@login_required
#@admin_required
@register_breadcrumb(user, ".", "Users")
def index():

    fact={}
    if "page" in request.args:
        fact["page"] = request.args.get("page", "")
    else:
        if "page" in fact:
            del fact["page"]

    r = sendRequest(method="get", url="/users", auth=True, data=json.dumps(fact))

    if r.status_code != 200:
        return redirect(url_for("user.index"))
    else:
        print(r.text)

        users = json.loads(r.text)["Users"]
        paginate = {}
        paginate["total"] = json.loads(r.text)["total"]
        paginate["pages"] = json.loads(r.text)["pages"]
        paginate["current_page"] = json.loads(r.text)["page"]
        title = "Users List"
        return render_template("users.html", title=title, users=users, pagination=paginate)


@user.route("/view/<int:id>")
@login_required
#@admin_required
@register_breadcrumb(user,".view","View")
def view(id):
    r = sendRequest(method="get", url="/user/"+str(id), auth=True)

    if (r.status_code == 404):
        flash("User not found","danger")
        return redirect(url_for("user.index"))
    user = json.loads(r.text)
    title = "User View"

    return render_template("user.html", title=title, user=user)

@user.route("/create", methods=["GET", "POST"])
@login_required
#@admin_required
@register_breadcrumb(user, ".create", "Create User")
def create():
    form = UserCreateForm()

    if form.validate_on_submit():
        user = {"email": form.email.data,"password": form.password.data, "admin": form.admin.data}
        data = json.dumps(user)
        r = sendRequest(method="post", url="/users", data=data, auth=True)
        return redirect(url_for("user.index"))

    return render_template("frmNewUser.html", form=form)

@user.route("/edit/<int:id>", methods=["GET","POST"])
@login_required
#@admin_required
@register_breadcrumb(user, ".edit", "Edit User")
def edit(id):
    form = UserEditForm()


    if not form.is_submitted():
        r = sendRequest(method="get", url="/user/"+str(id), auth=True)

        if (r.status_code == 404):
            flash("User not found","danger")
            return redirect(url_for("user.index"))

        user = json.loads(r.text)
        form.email.data = user["email"]
        form.admin.data = user["admin"]

    if form.validate_on_submit():
        user = {"email": form.email.data, "admin": form.admin.data}
        data = json.dumps(user)


        r = sendRequest(method="put", url="/user/"+str(id), data=data, auth=True)
        flash("User edited","success")
        return redirect(url_for("user.index"))

    return render_template("frmEditUser.html", form=form, id=id)

@user.route("/delete/<int:id>")
@login_required
#@admin_required
def delete(id):
    r = sendRequest(method="delete", url="/user/"+str(id), auth=True)
    flash("User deleted","danger")
    return redirect(url_for("user.index"))

seismology/web/main/routes/verifseism.py
from flask import Blueprint, redirect, render_template, request, url_for, flash, make_response
from flask_breadcrumbs import register_breadcrumb
from ..forms.frmLogin import LoginForm
import requests, json, io, csv
from ..utilities.Functions import sendRequest
from ..forms.frmSeisms import SeismFilterForm

verifseism = Blueprint("verifseism", __name__, url_prefix="/verified-seism")

@verifseism.route("/")
def index():
    frmLogin = LoginForm()
    filter = SeismFilterForm(request.args, meta={"csrf": False})
    r = sendRequest(method="get", url="/sensors-info")
    filter.sensorId.choices = [
        (int(sensor["id"]), sensor["name"]) for sensor in json.loads(r.text)["sensors"]
    ]
    filter.sensorId.choices.insert(0, [0, "All"])
    fact = {}

    if filter.validate():
        if filter.datetimeFrom.data and filter.datetimeTo.data:
            if filter.datetimeFrom.data == filter.datetimeTo.data:
                fact["datetime"] = filter.datetimeTo.data.strftime("%Y-%m-%d %H:%M")
        if filter.datetimeFrom.data != None:
            fact["datetimeFrom"] = filter.datetimeFrom.data.strftime("%Y-%m-%d %H:%M")
        if filter.datetimeTo.data != None:
            fact["datetimeTo"] = filter.datetimeTo.data.strftime("%Y-%m-%d %H:%M")

        if filter.sensorId.data != None and filter.sensorId.data != 0:
            fact["sensorId"] = filter.sensorId.data
        if filter.depth_min.data != None:
            fact["depth_min"] = filter.depth_min.data
        if filter.depth_max.data != None:
            fact["depth_max"] = filter.depth_max.data
        if filter.magnitude_min.data != None:
            fact["magnitude_min"] = filter.magnitude_min.data
        if filter.magnitude_max.data != None:
            fact["magnitude_max"] = filter.magnitude_max.data

    if "sort_by" in request.args:
        fact["sort_by"] = request.args.get("sort_by", "")

    if "download" in request.args:
        if request.args.get("download", "") == "Download":
            codeOK = 200
            page = 1
            SeismList = []

            while codeOK == 200:
                fact["page"] = page
                r = sendRequest(method="get", url="/verif-seisms", data=json.dumps(fact))
                codeOK = r.status_code

                if codeOK == 200:
                    for seism in json.loads(r.text)["Verif-seisms"]:
                        element = {"datetime": seism["datetime"], "depth": seism["depth"], "magnitude": seism["magnitude"],
                            "latitude": seism["latitude"], "longitude": seism["longitude"], "sensor.name": seism["sensor"]["name"]}
                        SeismList.append(element)
                page += 1

            si = io.StringIO()
            fc = csv.DictWriter(si, fieldnames=SeismList[0].keys())
            fc.writeheader()
            fc.writerows(SeismList)

            output = make_response(si.getvalue())
            output.headers["Content-Disposition"] = "attachment; filename=seisms.csv"
            output.headers["Content-type"] = "text/csv"
            return output

    if 'page' in request.args:
        fact["page"] = request.args.get("page", "")
    else:
        if 'page' in fact:
            del fact["page"]

    r = sendRequest(method="get", url="/verif-seisms", data=json.dumps(fact))

    if r.status_code == 200:
        verifseism = json.loads(r.text)["Verif-seisms"]
        paginate = {}
        paginate["total"] = json.loads(r.text)["total"]
        paginate["pages"] = json.loads(r.text)["pages"]
        paginate["current_page"] = json.loads(r.text)["page"]
        title = "Verified Seisms List"
        return render_template("Verified-Seisms.html", frmLogin=frmLogin, title=title, verified_seisms=verifseism, filter=filter, pagination=paginate)
    else:
        flash("Filtering Error", "danger")
        return redirect(url_for("verifseism.index"))


@verifseism.route("/view/<int:id>")
@register_breadcrumb(verifseism, ".view", "View")
def view(id):
    r = sendRequest(method="get", url="/verified-seism/" + str(id))

    if (r.status_code == 404):
        return redirect(url_for("verifseism.index"))

    verified_seism = json.loads(r.text)
    title = "Verified Seism View"
    loginForm = LoginForm()

    return render_template("verified-seism.html", frmLogin=loginForm, title=title, verified_seism=verified_seism)

seismology/web/main/templates/Sensor.html
{% extends "main.html" %}
{% import "macros.html" as macro %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-4 d-none d-md-block"></div>
            <div class="col-md-4">
                <div class="table-responsive text-center">
                    <table class="table table-dark table-striped table-hover table-bordered">
                        <caption>
                            <a name="modify" class="btn btn-success" href="{{url_for('sensor.edit',id=sensor.id)}}"
                                role="button">Modify</a>
                            <a name="delete" class="btn btn-danger" href="{{url_for('sensor.delete',id=sensor.id)}}"
                                role="button">Delete</a>
                        </caption>
                        <tbody>
                            <tr>
                                <th scope="row">ID</th>
                                <td>{{sensor.id}}</td>
                            </tr>
                            <tr>
                                <th scope="row">Name</th>
                                <td>{{sensor.name}}</td>
                            </tr>
                            <tr>
                                <th scope="row">IP</th>
                                <td>{{sensor.ip}}</td>
                            </tr>
                            <tr>
                                <th scope="row">PORT</th>
                                <td>{{sensor.port}}</td>
                            </tr>
                            <tr>
                                <th scope="row">Status</th>
                                <td>{{sensor.status}}</td>
                            </tr>
                            <tr>
                                <th scope="row">Active</th>
                                <td>{{sensor.active}}</td>
                            </tr>
                            <tr>
                                <th scope="row">User assigned</th>
                                <td>
                                    {% if sensor.user %}
                                        {{sensor.user.email}}
                                    {% endif %}
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="col-md-4 d-none d-md-block"></div>
        </div>
    </div>
{% endblock %}

seismology/web/main/templates/frmEditUser.html
{% extends "main.html" %} {# Herencia #}
{% import "macros.html" as macro %}
{% from "frmMacros.html" import show_field, show_submit %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-2 d-none d-md-block"></div>
            <div class="col-md-8">
                <form method="POST" action="{{ url_for('user.edit', id=id) }}">
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
                    <div class="form-group">
                        <div class="col-auto">{{ show_field(form.email, class="form-control") }}</div>
                    </div>
                    <div class="form-group align-items-center">
                        <div class="col-auto">{{ show_field(form.admin, class="form-check-label") }}</div>
                    </div>
                    <div class="col-auto">{{ show_submit(form.submit, class="btn btn-success") }}</div>
                </form>
            </div>
            <div class="col-md-2 d-none d-md-block"></div>
        </div>
    </div>
{% endblock %}

seismology/web/main/templates/frmMacros.html
{% macro show_error(field) %}
    {% if field.errors %}
        <div class="alert alert-danger my-1" role="alert">
          {% for error in field.errors %}
              {{ error }} <br>
          {% endfor %}
        </div>
    {% endif %}
{% endmacro %}

{% macro show_field(field) %}
    {{ field.label }}
    {{ field(**kwargs) | safe }}
    {{ show_error(field) }}
{% endmacro %}

{% macro show_placeholder(field) %}
    {{ field(placeholder=field.label.text, **kwargs) | safe }}
    {{ show_error(field) }}
{% endmacro %}

{% macro show_submit(field) %}
    {{ field(**kwargs) | safe }}
{% endmacro %}

{% macro show_checkbox(field) %}
    <div class="checkbox">
        <label>{{ field.label }} {{ field(type='checkbox', **kwargs) }}</label>
    </div>
{% endmacro %}

seismology/web/main/templates/frmSensorEdit.html
{% extends "main.html" %} {# Herencia #}
{% import "macros.html" as macro %}
{% from "frmMacros.html" import show_field, show_submit %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-2 d-none d-md-block"></div>
            <div class="col-md-8">
                <h1>Edit Sensor</h1>
                <form method="POST" action="{{ url_for('sensor.edit', id=id) }}">
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />

                    <div class="form-group">
                        <div class="col-auto">
                            {{ show_field(form.name, class="form-control") }}
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-auto">
                            {{ show_field(form.ip, class="form-control") }} <br>
                            {{ show_field(form.port, class="form-control") }} <br>
                            {{ show_field(form.status, type="checkbox") }} <br>
                            {{ show_field(form.active, type="checkbox") }} <br>
                            {{ show_field(form.userId, class="form-control") }} <br>
                        </div>

                        <div class="col-auto">
                            {{ show_submit(form.submit, class="btn btn-success") }}
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-md-2 d-none d-md-block"></div>
        </div>
    </div>
{% endblock %}

seismology/web/main/templates/macros.html
{% macro show_verified_seism(verifiedseism) %}
    <tr>
        <th scope="row">{{verifiedseism.id}}</th>
        <td>{{verifiedseism.datetime}}</td>
        <td>{{verifiedseism.depth}}</td>
        <td>{{verifiedseism.magnitude}}</td>
        <td>{{verifiedseism.sensor.name}}</td>
        <td>
            <div class="btn-group" role="group">
                <a class="btn btn-sm btn-dark" type="button" href="{{ url_for('verifseism.view', id=verifiedseism.id) }}">
                    <i class="fas fa-eye"></i></a>
                <a class="btn btn-sm btn-dark" type="button" href="#"><i class="fas fa-download"></i></a>
            </div>
        </td>
    </tr>
{% endmacro %}

{% macro show_unverified_seism(unverifiedseism) %}
    <tr>
        <th scope="row">{{unverified-seism.id}}</th>
        <td>{{unverifiedseism.datetime}}</td>
        <td>{{unverifiedseism.depth}}</td>
        <td>{{unverifiedseism.magnitude}}</td>
        <td>{{unverifiedseism.sensor.name}}</td>
        <td>
            <div class="btn-group" role="group">
                <a class="btn btn-sm btn-dark" type="button" href="{{url_for('unverified-seism.view',id=unverifiedseism.id)}}">
                    <i class="fas fa-eye"></i></a>
                <a class="btn btn-sm btn-dark" type="button" href="{{url_for('unverified-seism.edit',id=unverifiedseism.id)}}">
                    <i class="fas fa-edit"></i></a>
                <a class="btn btn-sm btn-dark" type="button" href="{{url_for('unverified-seism.delete', id=unverifiedseism.id)}}">
                    <i class="fas fa-trash"></i></a>
            </div>
        </td>
    </tr>
{% endmacro %}

{% macro show_user(user) %}
    <tr>
        <th scope="row">{{user.id}}</th>
        <td>{{user.email}}</td>
        <td>{{user.admin}}</td>
        <td>
            <div class="btn-group" role="group">
                <a class="btn btn-sm btn-dark" type="button" href="{{ url_for('user.view',id=user.id) }}">
                    <i class="fas fa-eye"></i></a>
                <a class="btn btn-sm btn-dark" type="button" href="{{url_for('user.edit', id=user.id)}}">
                    <i class="fas fa-edit"></i></a>
                <a class="btn btn-sm btn-dark" type="button" href="{{url_for('user.delete',id=user.id)}}">
                    <i class="fas fa-trash"></i></a>
            </div>
        </td>
    </tr>
{% endmacro %}

{% macro show_sensor(sensor) %}
    <tr>
        <th scope="row">{{sensor.id}}</th>
        <td>{{sensor.name}}</td>
        <td>{{sensor.status}}</td>
        <td>{{sensor.status}}</td>
        <td>
            {% if sensor.user %}
                {{sensor.user.email}}
            {% endif %}
        </td>
        <td>
            <div class="btn-group" role="group">
                <a class="btn btn-sm btn-dark" type="button" href="{{url_for('sensor.view',id=sensor.id)}}">
                    <i class="fas fa-eye"></i></a>
                <a class="btn btn-sm btn-dark" type="button" href="{{url_for('sensor.edit', id=sensor.id)}}">
                    <i class="fas fa-trash"></i></a>
                <a class="btn btn-sm btn-dark" type="button" href="{{url_for('sensor.delete',id=sensor.id)}}">
                    <i class="fas fa-edit"></i></a>
            </div>
        </td>
    </tr>
{% endmacro %}

seismology/web/main/templates/main.html
{% from "frmMacros.html" import show_field, show_submit, show_placeholder %}
<!DOCTYPE html>
<html lang="es">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{{title}}</title>

        {% block head %}
          <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
          <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
        {% endblock %}
    </head>

    <body>

        {% block scripts %}
          <script src="https://kit.fontawesome.com/ec398cbdc7.js"></script>
          <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
          <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
          <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
        {% endblock %}


        {% block menu %}
            <header>
                <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                    <a class="navbar-brand" href="{{url_for('main.index')}}">Seismology</a>

                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <div class="navbar-nav mr-auto">

                            {% if current_user.is_authenticated %}
                                {% if current_user.admin %}
                                    <a class="nav-item nav-link" href="{{url_for('sensor.index')}}">Sensors</a>
                                    <a class="nav-item nav-link" href="{{url_for('user.index')}}">Users</a>
                                {% endif %}
                            {% endif %}

                            {% if current_user.is_authenticated %}
                                <div class="navbar-nav text-light ml-auto">
                                    <a class="nav-item nav-link" href="#"><i>Logged in, {{ current_user.email }}</i></a>
                                    <a class="nav-item nav-link" href="{{ url_for('main.logout') }}"><i>Log Out</i></a>
                                </div>
                            {% else %}
                                <form class="form-inline" method="POST" action="{{ url_for('main.login') }}">
                                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                                    <div class="form-row">
                                        <div class="form-group col-md-5">
                                            {{ show_placeholder(frmLogin.email, class="form-control mr-sm-2") }}
                                        </div>
                                        <div class="form-group col-md-5">
                                            {{ show_placeholder(frmLogin.password, class="form-control") }}
                                        </div>
                                        <div class="form-group col-md-2">
                                            {{ show_submit(frmLogin.submit, class="btn btn-success") }}
                                        </div>
                                    </div>
                                </form>
                            {% endif %}
                        </div>
                    </div>
                </nav>
            </header>
        {% endblock %}


        {% block breadcrumbs %}
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb bg-dark">
                    {% for breadcrumb in breadcrumbs %}
                        <li class="breadcrumb-item">
                            {% if not loop.last %}
                                <a class="text-light" href="{{ breadcrumb.url }}">{{ breadcrumb.text }}</a>
                            {% else %}
                                {{ breadcrumb.text }}
                                {{ "/" if not loop.last }}
                            {% endif %}
                        </li>
                    {% endfor %}
                </ol>
            </nav>
        {% endblock %}

        {% block flash %}
            <div class="container-fluid">
                <div style="position: relative">
                    <div style="position: absolute; top: 0; right: 0;">
                        <div class="col-auto mx-auto">
                            {% with messages = get_flashed_messages(with_categories=true) %}
                                {% if messages %}
                                    {% for category, message in messages %}
                                        <div class="alert alert-{{category}} alert-dismissible fade show" role="alert">
                                            {{ message }}
                                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                    {% endfor %}
                                {% endif %}
                            {% endwith %}
                        </div>
                    </div>
                </div>
            </div>
        {% endblock %}

        <main>
            {% block content %}
            {% endblock %}
        </main>

        {% block footer %}
            <footer class="page-footer bg-dark pt-4" with=100%>
                <div class="container">
                    <div class="footer-copyright text-center py-2"><a href="#">Copyright - Seismology 2020</a>
                    </div>
                </div>
            </footer>
        {% endblock %}
    </body>
</html>

seismology/web/main/templates/user.html
{% extends "main.html" %}
{% import "macros.html" as macro %}

{% block content %}
    <div class="row justify-content-center">
        <div class="col-md-auto d-none d-md-block"></div>
        <div class="col-md-auto">
            <hr class="bg-white mb-5"/>

            <table class="table table-bordered table-responsive">
                <caption>
                    <a name="modify" class="btn btn-success" href="{{url_for('user.edit',id=user.id)}}"
                    role="button">Modify</a>
                    <a name="delete" class="btn btn-danger" href="{{url_for('user.delete',id=user.id)}}"
                    role="button">Delete</a>
                </caption>

                <tbody>
                    <tr>
                        <th scope="row">ID</th>
                        <td>{{user.id}}</td>
                    </tr>
                    <tr>
                        <th scope="row">Email</th>
                        <td>{{user.email}}</td>
                    </tr>
                    <tr>
                        <th scope="row">Admin</th>
                        <td>{{user.admin}}</td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="col-md-auto d-none d-md-block thead-dark"></div>
    </div>
{% endblock %}